apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  name: #<modelName>
  namespace: aaw-team
spec:
  #slotsPerWorker: Tensorflow example sets this attribute, but Pat's example template doesn't.
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        metadata:
          labels:
            data.statcn.gc.ca/inject-blob-volumes: 'true' # Access blob storage.
            sidecar.istio.io/inject: "false" # Init container conflicts with istio.
        spec:
          containers:
          - image: k8scc01covidacr.azurecr.io/ompp-run-ubuntu:d1174244baa102b26f0850c3883e7b15c50a3b64
            # There must be a better way than just hardcoding these image names in here, right?
            name: #<modelName>-launcher
            command:
            - mpirun
            #<mpirunOption>
            #<modelExecutable>
            #<OpenMOption>
            resources:
              limits:
                cpu: '2'
                memory: 2Gi
              requests:
                cpu: 250m
                memory: 250Mi

    Worker:
      replicas: #<numberOfReplicas>
      template:
        spec:
          containers:
          - image: k8scc01covidacr.azurecr.io/ompp-run-ubuntu:d1174244baa102b26f0850c3883e7b15c50a3b64
            # Same as above, I don't think this should be hardcoded in like this.
            name: #<modelName>-worker
            resources:
                limits:
                  cpu: '2'
                  memory: 2Gi
                requests:
                  cpu: '2'
                  memory: 1Gi

            # In the tensorflow example there are volume and volume mount definitions for the worker pods.
            # I don't think this is necessary if the container images used in the worker pod definitions
            # have COPY directives that populate the ephemeral filesystem with the required files.
